[package]
name = "ds3231"
version = "0.1.0"
authors = ["liebman <liebman@zod.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bilge = { version = "0.2.0", git = "https://github.com/hecatia-elegua/bilge.git", rev = "41843c8"}
chrono = { version = "0.4.31", default-features = false, features = [] }
embedded-hal = { version = "=1.0.0-rc.2" }
embedded-hal-async = { version = "=1.0.0-rc.2" }
log = { version = "0.4.20" }
paste = { version = "1.0.14" }
