coverage:
  range: 70..100
  round: down
  precision: 1

  status:
    project:
      default:
        target: 85%
        threshold: 1%
        if_no_uploads: error
    patch:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: header, diff, flags, files
  behavior: default
  require_changes: false

ignore:
  - "**/*.rs"  # Ignore specific patterns if needed

github_checks:
  annotations: true 