name: Changelog Check

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  changelog-check:
    name: Check CHANGELOG Entry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check for CHANGELOG entry
        uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: 'CHANGELOG.md'
          skipLabels: 'skip-changelog,dependencies'
          missingUpdateErrorMessage: |
            We require a CHANGELOG entry for all pull requests except those labeled with 'skip-changelog' or 'dependencies'.
            
            Please add an entry to CHANGELOG.md under the [Unreleased] section describing your changes.
            
            The CHANGELOG.md follows the Keep a Changelog format:
            - Add new features under '### Added'
            - Add changes under '### Changed' 
            - Add deprecations under '### Deprecated'
            - Add removals under '### Removed'
            - Add bug fixes under '### Fixed'
            - Add security fixes under '### Security'
            
            If this PR doesn't require a changelog entry (e.g., documentation updates, CI changes), 
            please add the 'skip-changelog' label to this PR.
          expectedLatestVersion: 'Unreleased' 